# Generated by Django 4.0.5 on 2022-06-03 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('data_de_lancamento', models.DateField()),
                ('sinopse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('estilo', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Gênero',
            },
        ),
        migrations.CreateModel(
            name='Roteirista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=16)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_aluguel', models.DateTimeField(auto_now_add=True)),
                ('prazo_devolucao', models.DateTimeField()),
                ('datetime_devolucao', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.filme')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aluguéis',
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filme')),
                ('roteirista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roteirista')),
            ],
            options={
                'unique_together': {('roteirista', 'filme')},
            },
        ),
        migrations.CreateModel(
            name='Direcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diretor')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filme')),
            ],
            options={
                'verbose_name': 'Direção',
                'verbose_name_plural': 'Direções',
                'unique_together': {('diretor', 'filme')},
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filme')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'unique_together': {('genero', 'filme')},
            },
        ),
    ]
