# Generated by Django 4.0.5 on 2022-06-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filme_qtd_copias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='direcao',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='direcao',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='direcao',
            name='filme',
        ),
        migrations.AlterUniqueTogether(
            name='roteiro',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='filme',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='roteirista',
        ),
        migrations.AddField(
            model_name='filme',
            name='diretores',
            field=models.ManyToManyField(to='core.diretor'),
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(to='core.genero'),
        ),
        migrations.AddField(
            model_name='filme',
            name='roteiristas',
            field=models.ManyToManyField(to='core.roteirista'),
        ),
        migrations.DeleteModel(
            name='Classificacao',
        ),
        migrations.DeleteModel(
            name='Direcao',
        ),
        migrations.DeleteModel(
            name='Roteiro',
        ),
    ]
